// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetUmbracoSubscriptionsApiV1GetActiveResponse, GetUmbracoSubscriptionsApiV1GetExpiredResponse, GetUmbracoSubscriptionsApiV1GetNonsubscribedResponse } from './types.gen';

export class SubscriptionsApiService {
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getUmbracoSubscriptionsApiV1GetActive(): CancelablePromise<GetUmbracoSubscriptionsApiV1GetActiveResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/subscriptions/api/v1/GetActive'
        });
    }
    
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getUmbracoSubscriptionsApiV1GetExpired(): CancelablePromise<GetUmbracoSubscriptionsApiV1GetExpiredResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/subscriptions/api/v1/GetExpired'
        });
    }
    
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getUmbracoSubscriptionsApiV1GetNonsubscribed(): CancelablePromise<GetUmbracoSubscriptionsApiV1GetNonsubscribedResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/subscriptions/api/v1/GetNonsubscribed'
        });
    }
    
}