// This file is auto-generated by @hey-api/openapi-ts

export type SubscriptionListItem = {
    memberKey: string;
    firstName?: (string) | null;
    lastName?: (string) | null;
    email?: (string) | null;
    subscriptionExpiry?: (string) | null;
};

export type GetUmbracoSubscriptionsApiV1GetActiveResponse = (Array<(SubscriptionListItem)>);

export type GetUmbracoSubscriptionsApiV1GetExpiredResponse = (Array<(SubscriptionListItem)>);

export type GetUmbracoSubscriptionsApiV1GetNonsubscribedResponse = (Array<(SubscriptionListItem)>);